### PR TITLE
fix: reduce overview open lag

### LINKED ISSUE #22: Massive lag when calling up the window overview
Hi

when i have the extension active and call up the window overview, it takes almost a second before there is any reaction at all. If I deactivate the extension, it works immediately.
Neither CPU nor GPU show increased load.

### PR DESCRIPTION
**Pull request by elkhaligy**
## Summary

   - Cache `Gio.Settings` object and fractional scaling result in
   `windowScaleFactor()` — was allocating a new GSettings object on
   every call, which runs per-frame × per-window inside
   `vfunc_allocate` during overview animations (60fps × N windows)
   - Replace `new Error().stack` call stack inspection in
   `addShadowInOverview` with `window.get_transient_for()` to detect
   attached dialogs — stack trace capture fired for every window on
   every overview open
   - Deduplicate `getPref('global-rounded-corner-settings')` calls in
   `updateShadowActorStyle` from 3-4x down to 1x per call
   - Skip `queue_redraw()` when the shadow style string hasn't changed,
    avoiding unnecessary GPU repaints on focus changes
   - Prune disconnected entries from `connections[]` array on window
   close, preventing unbounded growth over the session

   ## Root cause

   The main bottleneck was `windowScaleFactor()` calling
   `Gio.Settings.new('org.gnome.mutter')` on every invocation. This
   function is called from `vfunc_allocate` on the overview shadow
   clone actors, which Clutter calls on every layout pass during
   overview animations, meaning every frame × every window was
   allocating a new GSettings object and reading from the GSettings
   daemon. The fix caches the settings object and the derived boolean
   at module level, invalidating only when `experimental-features`
   actually changes.

Closes #22

### CODE REVIEW

File: src/manager/utils.ts [hunk 1]
```diff
@@ -8,6 +8,36 @@ import Gio from 'gi://Gio';
...
+
+function getMutterSettings(): Gio.Settings {
+    if (_mutterSettings === null) {
+        _mutterSettings = Gio.Settings.new('org.gnome.mutter');
+        _mutterSettings.connect('changed::experimental-features', () => {
+            _fractionalScalingEnabled = null;
+        });
+    }
+    return _mutterSettings;
+}
```
Comment (flexagoon) [inline src/manager/utils.ts]: Since this is only called inside of `isFractionalScalingEnabled()`, it should probably just be moved inside of it instead of being a separate function. That would also make more sense because the experimental-features signal is connected here.
